#!/usr/bin/env python3
"""
ForgeKeep — Excel importer.

Reads the master inventory workbook and emits an idempotent SQL seed file that
can be applied in the Supabase SQL editor (or via psql). Re-running a future
export of the same workbook UPSERTs by `import_key`, so rows update instead of
duplicating.

Usage:
    python import_excel.py INPUT.xlsx -o seed.generated.sql
    # then paste seed.generated.sql into Supabase Studio > SQL Editor and Run,
    # AFTER you have created your account (it binds rows to the first auth user).

Optional direct push (requires network + DATABASE_URL):
    DATABASE_URL=postgres://... python import_excel.py INPUT.xlsx --push
"""
import argparse, hashlib, os, re, sys
from collections import Counter
import openpyxl

# ---------- helpers ----------------------------------------------------------
def q(v):
    """SQL-quote a value -> 'literal' or NULL."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return repr(v)
    s = str(v).strip()
    if s == "":
        return "NULL"
    return "'" + s.replace("'", "''") + "'"

def key(*parts):
    raw = "|".join("" if p is None else str(p) for p in parts)
    return hashlib.md5(raw.encode()).hexdigest()

def rows(ws):
    it = ws.iter_rows(values_only=True)
    headers = next(it)
    for r in it:
        if all(c is None for c in r):
            continue
        yield dict(zip(headers, r))

def num(v, default=None):
    if v is None:
        return default
    if isinstance(v, (int, float)):
        return int(v)
    m = re.search(r"\d+", str(v))
    return int(m.group()) if m else default

# ---------- paint-status -> seeded stage counts ------------------------------
def seed_painted(paint_status, qty):
    if not paint_status:
        return 0
    s = str(paint_status)
    m = re.search(r"Painted\s*\((\d+)\)", s, re.I)   # "Painted (32) / Unpainted (3)"
    if m:
        return min(int(m.group(1)), qty)
    low = s.lower()
    if low == "painted":
        return qty
    if "mostly painted" in low:
        return round(qty * 0.8)
    if "partially painted" in low:
        return round(qty * 0.4)
    return 0

def seed_assembled(assembly_status, qty):
    if not assembly_status:
        return 0
    low = str(assembly_status).lower()
    if low == "assembled":
        return qty
    if low == "mixed":
        return qty            # at least built; user refines later
    return 0                   # NiB / NOS / Partial / Unknown

# ---------- main -------------------------------------------------------------
def build_sql(path):
    wb = openpyxl.load_workbook(path, data_only=True)
    out = []
    w = out.append

    w("-- Generated by import_excel.py — idempotent (UPSERT by import_key).")
    w("-- Apply AFTER creating your account. Binds to the first auth user.")
    w("-- Ensure barcode columns exist so this seed applies cleanly whether or")
    w("-- not migration 0007 has been run yet (backward compatible).")
    w("alter table miniature_units add column if not exists barcode text;")
    w("alter table paints  add column if not exists barcode text;")
    w("alter table tools   add column if not exists barcode text;")
    w("alter table terrain add column if not exists barcode text;")
    w("do $$")
    w("declare v_owner uuid;")
    w("begin")
    w("  select id into v_owner from auth.users order by created_at limit 1;")
    w("  if v_owner is null then")
    w("    raise exception 'No auth user found. Sign up in the app first, then re-run.';")
    w("  end if;")
    w("")
    w("  -- Game system (single default).")
    w("  insert into game_systems(owner_id,name,slug) values "
      "(v_owner,'Warhammer 40,000','warhammer-40k') "
      "on conflict (owner_id,name) do nothing;")
    w("")

    # ---- Factions (distinct from Miniatures) --------------------------------
    factions = []
    if "Miniatures" in wb.sheetnames:
        seen = set()
        for r in rows(wb["Miniatures"]):
            f = r.get("Faction")
            if f and f not in seen:
                seen.add(f); factions.append(f)
    w("  -- Factions")
    for f in factions:
        w(f"  insert into factions(owner_id,game_system_id,name) values "
          f"(v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),{q(f)}) "
          f"on conflict (owner_id,name) do nothing;")
    w("")

    # ---- Projects derived from Priority values containing 'Project' ---------
    projects = []
    if "Miniatures" in wb.sheetnames:
        seen = set()
        for r in rows(wb["Miniatures"]):
            pri, fac = r.get("Priority"), r.get("Faction")
            if pri and "project" in str(pri).lower():
                nm = f"{fac} — {pri}"
                if nm not in seen:
                    seen.add(nm); projects.append((nm, fac, pri))
    w("  -- Projects (derived from 'Project' priorities so progress bars have data)")
    for nm, fac, pri in projects:
        w(f"  insert into projects(owner_id,name,faction_id,priority,status) values "
          f"(v_owner,{q(nm)},(select id from factions where owner_id=v_owner and name={q(fac)}),{q(pri)},'Active') "
          f"on conflict do nothing;")
    w("")

    # ---- Miniatures ---------------------------------------------------------
    if "Miniatures" in wb.sheetnames:
        w("  -- Miniature units")
        for r in rows(wb["Miniatures"]):
            fac = r.get("Faction"); unit = r.get("Unit")
            if not unit:
                continue
            qty = num(r.get("Quantity"), 1) or 0
            pri = r.get("Priority")
            paint = r.get("Paint Status")
            ik = key(fac, unit, pri, r.get("Loadout / Notes"), r.get("Material"))
            proj = f"{fac} — {pri}" if pri and "project" in str(pri).lower() else None
            painted = seed_painted(paint, qty)
            assembled = seed_assembled(r.get("Assembly Status"), qty)
            w("  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,"
              "unit_name,quantity,material,paint_status,assembly_status,basing_status,"
              "repairs_needed,tabletop_ready,priority,notes,estimated_value,"
              "qty_assembled,qty_painted,barcode,import_key) values (")
            w("    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),")
            w(f"    (select id from factions where owner_id=v_owner and name={q(fac)}),")
            w(f"    {('(select id from projects where owner_id=v_owner and name='+q(proj)+')') if proj else 'NULL'},")
            w(f"    {q(unit)},{qty},{q(r.get('Material'))},{q(paint)},{q(r.get('Assembly Status'))},"
              f"{q(r.get('Basing Status'))},{q(r.get('Repairs Needed'))},{q(r.get('Tabletop Ready'))},"
              f"{q(pri)},{q(r.get('Loadout / Notes'))},{num(r.get('Estimated Value'),0) or 0},")
            w(f"    {assembled},{painted},{q(r.get('Barcode'))},{q(ik)}")
            w("  ) on conflict (owner_id,import_key) do update set "
              "quantity=excluded.quantity,paint_status=excluded.paint_status,"
              "assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,"
              "repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,"
              "priority=excluded.priority,notes=excluded.notes,barcode=excluded.barcode,updated_at=now();")
        w("")

    # ---- Paints -------------------------------------------------------------
    if "Paints" in wb.sheetnames:
        w("  -- Paints")
        occ = Counter()
        for r in rows(wb["Paints"]):
            brand = r.get("Brand"); color = r.get("Color / Product")
            if not (brand and color):
                continue
            line = r.get("Line")
            occ[(brand, line, color)] += 1
            ik = key(brand, line, color, occ[(brand, line, color)])
            needs = r.get("Needs Replacement?") or "No"
            w("  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,"
              "condition,opened,needs_replacement,notes,barcode,import_key) values (")
            w(f"    v_owner,{q(r.get('Category'))},{q(brand)},{q(line)},{q(color)},"
              f"{num(r.get('Quantity'),1) or 1},{q(r.get('Paint Type'))},{q(r.get('Condition'))},"
              f"{q(r.get('Opened?'))},{q(needs)},{q(r.get('Notes'))},{q(r.get('Barcode'))},{q(ik)}")
            w("  ) on conflict (owner_id,import_key) do update set "
              "quantity=excluded.quantity,condition=excluded.condition,"
              "needs_replacement=excluded.needs_replacement,notes=excluded.notes,barcode=excluded.barcode,updated_at=now();")
        w("")

    # ---- Brushes ------------------------------------------------------------
    if "Brushes" in wb.sheetnames:
        w("  -- Brushes")
        occ = Counter()
        for r in rows(wb["Brushes"]):
            mfr = r.get("Brand")
            if not mfr:
                continue
            series = r.get("Series / Type"); size = r.get("Size")
            occ[(mfr, series, size)] += 1
            ik = key(mfr, series, size, occ[(mfr, series, size)])
            w("  insert into brushes(owner_id,manufacturer,series,size,material,quantity,"
              "condition,purpose,notes,import_key) values (")
            w(f"    v_owner,{q(mfr)},{q(series)},{q(size)},{q(r.get('Hair / Material'))},"
              f"{num(r.get('Quantity'),1) or 1},{q(r.get('Condition'))},{q(r.get('Primary Use'))},"
              f"{q(r.get('Notes'))},{q(ik)}")
            w("  ) on conflict (owner_id,import_key) do update set "
              "quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();")
        w("")

    # ---- Tools --------------------------------------------------------------
    if "Tools_Equipment" in wb.sheetnames:
        w("  -- Tools / Equipment")
        occ = Counter()
        for r in rows(wb["Tools_Equipment"]):
            item = r.get("Item")
            if not item:
                continue
            cat = r.get("Category")
            occ[(cat, item)] += 1
            ik = key(cat, item, occ[(cat, item)])
            w("  insert into tools(owner_id,category,item,quantity,condition,notes,barcode,import_key) values (")
            w(f"    v_owner,{q(cat)},{q(item)},{num(r.get('Quantity'),1) or 1},"
              f"{q(r.get('Condition'))},{q(r.get('Notes'))},{q(r.get('Barcode'))},{q(ik)}")
            w("  ) on conflict (owner_id,import_key) do update set "
              "quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,barcode=excluded.barcode,updated_at=now();")
        w("")

    # ---- Terrain ------------------------------------------------------------
    if "Terrain" in wb.sheetnames:
        w("  -- Terrain")
        occ = Counter()
        for r in rows(wb["Terrain"]):
            tset = r.get("Terrain Set")
            if not tset:
                continue
            comp = r.get("Component")
            occ[(tset, comp)] += 1
            ik = key(tset, comp, occ[(tset, comp)])
            qn = num(r.get("Quantity"))
            qlabel = None if qn is not None else r.get("Quantity")
            w("  insert into terrain(owner_id,terrain_set,components,quantity,quantity_label,"
              "paint_status,repairs_needed,notes,barcode,import_key) values (")
            w(f"    v_owner,{q(tset)},{q(comp)},{q(qn)},{q(qlabel)},"
              f"{q(r.get('Paint Status'))},{q(r.get('Repairs Needed'))},{q(r.get('Notes'))},{q(r.get('Barcode'))},{q(ik)}")
            w("  ) on conflict (owner_id,import_key) do update set "
              "quantity=excluded.quantity,paint_status=excluded.paint_status,"
              "repairs_needed=excluded.repairs_needed,notes=excluded.notes,barcode=excluded.barcode,updated_at=now();")
        w("")

    w("  raise notice 'Import complete for owner %', v_owner;")
    w("end $$;")
    return "\n".join(out)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("-o", "--output", default="seed.generated.sql")
    ap.add_argument("--push", action="store_true",
                    help="Apply directly via DATABASE_URL (needs network + psql).")
    a = ap.parse_args()
    sql = build_sql(a.input)
    with open(a.output, "w") as f:
        f.write(sql + "\n")
    print(f"Wrote {a.output} ({len(sql.splitlines())} lines).")
    if a.push:
        url = os.environ.get("DATABASE_URL")
        if not url:
            sys.exit("DATABASE_URL not set.")
        import subprocess
        subprocess.run(["psql", url, "-f", a.output], check=True)
        print("Pushed to database.")

if __name__ == "__main__":
    main()
