-- Generated by import_excel.py — idempotent (UPSERT by import_key).
-- Apply AFTER creating your account. Binds to the first auth user.
do $$
declare v_owner uuid;
begin
  select id into v_owner from auth.users order by created_at limit 1;
  if v_owner is null then
    raise exception 'No auth user found. Sign up in the app first, then re-run.';
  end if;

  -- Game system (single default).
  insert into game_systems(owner_id,name,slug) values (v_owner,'Warhammer 40,000','warhammer-40k') on conflict (owner_id,name) do nothing;

  -- Factions
  insert into factions(owner_id,game_system_id,name) values (v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),'Thousand Sons') on conflict (owner_id,name) do nothing;
  insert into factions(owner_id,game_system_id,name) values (v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),'Orks') on conflict (owner_id,name) do nothing;
  insert into factions(owner_id,game_system_id,name) values (v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),'Aeldari') on conflict (owner_id,name) do nothing;
  insert into factions(owner_id,game_system_id,name) values (v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),'Necrons') on conflict (owner_id,name) do nothing;
  insert into factions(owner_id,game_system_id,name) values (v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),'Aeldari/Ynnari') on conflict (owner_id,name) do nothing;

  -- Projects (derived from 'Project' priorities so progress bars have data)
  insert into projects(owner_id,name,faction_id,priority,status) values (v_owner,'Thousand Sons — Active Project',(select id from factions where owner_id=v_owner and name='Thousand Sons'),'Active Project','Active') on conflict do nothing;
  insert into projects(owner_id,name,faction_id,priority,status) values (v_owner,'Thousand Sons — Secondary Project',(select id from factions where owner_id=v_owner and name='Thousand Sons'),'Secondary Project','Active') on conflict do nothing;

  -- Miniature units
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Thousand Sons'),
    (select id from projects where owner_id=v_owner and name='Thousand Sons — Active Project'),
    'Rubric Marines',8,'Plastic','Unpainted','Assembled','Unknown','None','No','Active Project','1 Warpflamer, 1 Soulreaper Cannon',0,
    8,0,'8b41741cf4afa665f30ce95ffdf21708'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Thousand Sons'),
    (select id from projects where owner_id=v_owner and name='Thousand Sons — Active Project'),
    'Aspiring Sorcerer',1,'Plastic','Unpainted','Assembled','Unknown','None','No','Active Project',NULL,0,
    1,0,'9b32542a586ee2ecb5c4ed99b3b0cca2'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Thousand Sons'),
    (select id from projects where owner_id=v_owner and name='Thousand Sons — Active Project'),
    'Scarab Occult Terminators',2,'Plastic','Unpainted','Assembled','Unknown','None','No','Active Project','1 Soulreaper Cannon',0,
    2,0,'0501459665bb1ac009dbe287bec26290'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Thousand Sons'),
    (select id from projects where owner_id=v_owner and name='Thousand Sons — Active Project'),
    'Scarab Occult Sorcerer',1,'Plastic','Unpainted','Assembled','Unknown','None','No','Active Project',NULL,0,
    1,0,'6d8bfaae39c5cf46ee2bc3ce9f7b2e77'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Orks'),
    NULL,
    'Shoota Boyz',35,'Plastic','Painted (32) / Unpainted (3)','Assembled','Old bases','Rebase to current size','No','Backlog','1 Big Shoota included',0,
    35,32,'62a9fcd90f6b1c6251c539b26bbb0471'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Orks'),
    NULL,
    'Slugga Boyz',72,'Plastic','Mostly Painted','Assembled','Old bases','Rebase to current size','No','Backlog','Combined across cases',0,
    72,58,'abf15cbb7eecaf1972e7bd06f884c9bd'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Orks'),
    NULL,
    'Gretchin',93,'Mixed','Mostly Unpainted','Assembled','Mixed','Rebase older models','No','Backlog','Includes vintage and modern grots',0,
    93,0,'4c877ed5b39597bf086020334359633f'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Orks'),
    NULL,
    'Lootas',18,'Plastic','Mostly Unpainted','Assembled','Old bases','Rebase','No','Backlog',NULL,0,
    18,0,'eea752ba01b715304e4c52971180cc8d'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Orks'),
    NULL,
    'Burna Boyz',21,'Mixed','Mostly Unpainted','Assembled','Old bases','Rebase','No','Backlog',NULL,0,
    21,0,'06600e340063e7bee106d5c88e9a9f9c'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Orks'),
    NULL,
    'Stormboyz',9,'Mixed','Mostly Painted','Assembled','Old bases','Rebase','No','Backlog','Includes Nob with Power Klaw',0,
    9,7,'b691636514da51ebf4159cf4bc64eb5d'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Orks'),
    NULL,
    'Nobz',8,'Mixed','Mixed','Assembled','Old bases','Rebase','No','Backlog','Various loadouts incl. PK and Big Choppas',0,
    8,0,'4d3a2c8aa9caa153451767ff57468ccf'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Orks'),
    NULL,
    'Painboy',1,'Metal','Painted','Assembled','Old base','Rebase','No','Backlog','Classic metal Painboy',0,
    1,1,'5142e20e484ccb4c1c16c1d3aa14bb67'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Thousand Sons'),
    (select id from projects where owner_id=v_owner and name='Thousand Sons — Secondary Project'),
    'Rubric Marines',20,'Plastic','NiB + Built Squad','Mixed','Current','None','No','Secondary Project','2 NiB boxes plus built squad',0,
    20,0,'3e2aeecfbd5d0bcad4c11d7870c74a68'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Thousand Sons'),
    (select id from projects where owner_id=v_owner and name='Thousand Sons — Secondary Project'),
    'Scarab Occult Terminators',5,'Plastic','NiB','NiB','Current','None','No','Secondary Project',NULL,0,
    0,0,'6946b155839b864257a6863f54437502'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Thousand Sons'),
    (select id from projects where owner_id=v_owner and name='Thousand Sons — Secondary Project'),
    'Exalted Sorcerers',6,'Plastic','NiB + 1 painted','Mixed','Current','One painted model needs reassembly','Partial','Secondary Project',NULL,0,
    6,0,'36529f3cf37c79181a6ef7bd8e5eb8a1'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Thousand Sons'),
    (select id from projects where owner_id=v_owner and name='Thousand Sons — Secondary Project'),
    'Daemon Prince',2,'Plastic','NiB','NiB','Current','None','No','Secondary Project','AoS kit',0,
    0,0,'69d1e24cbbffb5082b7c716e8c6eff3f'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Thousand Sons'),
    (select id from projects where owner_id=v_owner and name='Thousand Sons — Secondary Project'),
    'Flamers of Tzeentch',6,'Plastic','NiB','NiB','Current','None','No','Secondary Project',NULL,0,
    0,0,'3fb35f4a6e7e873519efd3b73766f090'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Thousand Sons'),
    (select id from projects where owner_id=v_owner and name='Thousand Sons — Secondary Project'),
    'Hexfire Box',1,'Box Set','NiB','NiB','Current','None','No','Secondary Project','Untouched',0,
    0,0,'dd0b1a9efacd6147d2a8b36027c2a57b'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Aeldari'),
    NULL,
    'Warlocks',29,'Mixed','Mostly Unpainted','Assembled','Current','None','No','Storage','Count found during inventory only',0,
    29,0,'c48f5c8550839b203ff4b231914e0c55'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Aeldari'),
    NULL,
    'Farseers',5,'Mixed','Mostly Unpainted','Assembled','Current','None','No','Storage','Includes Eldrad separately',0,
    5,0,'3fa0f3d2914f7bffa7ca590b9fe9eda9'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Aeldari'),
    NULL,
    'Eldrad Ulthran',1,'Metal','Unpainted','Assembled','Current','None','No','Storage',NULL,0,
    1,0,'9f228338c14c4491ad420bbd54f904ad'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Aeldari'),
    NULL,
    'Asurmen',1,'Metal/Finecast','Unpainted','Assembled','Current','None','No','Storage',NULL,0,
    1,0,'359f7122f5595ee969a90a2dbc8d80c9'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Aeldari'),
    NULL,
    'Prince Yriel',1,'Metal','Unpainted','Assembled','Current','None','No','Storage',NULL,0,
    1,0,'4e212f7a1e2695f908cf6ed16a7072ef'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Aeldari'),
    NULL,
    'Dire Avengers',24,'Plastic','Mostly Unpainted','Assembled','Current','None','No','Storage','Plus 2 Exarchs',0,
    24,0,'ba4e07708f881a0f71e31c2ed458552b'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Aeldari'),
    NULL,
    'Wraithguard',8,'Metal','Unpainted','Assembled','Current','None','No','Storage',NULL,0,
    8,0,'c954bd3c301cfc4420035ee69f40b2e7'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Aeldari'),
    NULL,
    'Rangers',16,'Metal','Unpainted','Assembled','Current','None','No','Storage',NULL,0,
    16,0,'2fc3342ca087405edfdb67807580f8ee'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Aeldari'),
    NULL,
    'Fire Dragons',7,'Metal','Unpainted','Assembled','Current','None','No','Storage','Includes Exarch',0,
    7,0,'a2ed8619654110bea9bfa087af9c2038'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Aeldari'),
    NULL,
    'Howling Banshees',9,'Metal','Mixed','Assembled','Current','None','No','Storage','Includes Exarch',0,
    9,0,'1de199f8366485fb157f3f449e294509'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Aeldari'),
    NULL,
    'Striking Scorpions',8,'Mixed','Mostly Unpainted','Assembled','Current','None','No','Storage','Includes Exarch',0,
    8,0,'862b648882d6549adcf191cf8ed0cdd8'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Aeldari'),
    NULL,
    'Swooping Hawks',4,'Metal','Unpainted','Assembled','Current','None','No','Storage',NULL,0,
    4,0,'a5500e48eb80bbc3587496c2ae977578'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Aeldari'),
    NULL,
    'Harlequins',6,'Metal','Unpainted','Assembled','Current','None','No','Storage','Troupe, Master, Shadowseer',0,
    6,0,'4e71da67879bd4d7e8665a9d03e72c6a'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Aeldari'),
    NULL,
    'Bonesingers',2,'Metal','Unpainted','Assembled','Current','None','No','Storage',NULL,0,
    2,0,'7a6fa1808060a4c56a0779b6801e0ad0'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Aeldari'),
    NULL,
    'Illic Nightspear',1,'Finecast','Unpainted','Assembled','Current','None','No','Storage',NULL,0,
    1,0,'970afeca36857720d42aaf553742aa90'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Necrons'),
    NULL,
    'Ophydian Destroyers',4,'Plastic','NiB','NiB','Current','None','No','Storage',NULL,0,
    0,0,'6ecf6ad14d390c90be4d3bd8eba908f0'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();
  insert into miniature_units(owner_id,game_system_id,faction_id,project_id,unit_name,quantity,material,paint_status,assembly_status,basing_status,repairs_needed,tabletop_ready,priority,notes,estimated_value,qty_assembled,qty_painted,import_key) values (
    v_owner,(select id from game_systems where owner_id=v_owner and name='Warhammer 40,000'),
    (select id from factions where owner_id=v_owner and name='Aeldari/Ynnari'),
    NULL,
    'Triumvirate of Ynnead',1,'Plastic','NiB','NiB','Current','None','No','Storage','Boxed set',0,
    0,0,'85e1e70450cea5a0bda5ef7ad33ee2ce'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,assembly_status=excluded.assembly_status,basing_status=excluded.basing_status,repairs_needed=excluded.repairs_needed,tabletop_ready=excluded.tabletop_ready,priority=excluded.priority,notes=excluded.notes,updated_at=now();

  -- Paints
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Bold Titanium White',1,'Acrylic','New','Unknown','No','From Base Set','50ac787ab8366f0c6143a138b9dafc20'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Coal Black',1,'Acrylic','New','Unknown','No','From Base Set','6237b1f51adc790d3dd99b4e01cb1014'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Bold Pyrrole Red',1,'Acrylic','New','Unknown','No','From Base Set','c70e78a4f5caeffee7455795eac042b4'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Green',1,'Acrylic','New','Unknown','No','From Base Set','e8b185e1566b8a399d5b7452bf0cb4c6'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Blue',1,'Acrylic','New','Unknown','No','From Base Set','4f0983d1755c724ae8d537f73daf1904'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Golden Yellow',1,'Acrylic','New','Unknown','No','From Base Set','3d0533ef874acfcacbf9c3c9c391ef29'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Orange',1,'Acrylic','New','Unknown','No','From Base Set','bc25cb7748b6110dc49406dc44d0814a'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Burnt Red',1,'Acrylic','New','Unknown','No','From Base Set','76f657464d9529bc1fd0c59409469250'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Mahogany',1,'Acrylic','New','Unknown','No','From Base Set','ba1218523d052273321235ddf41dc0aa'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Purple',1,'Acrylic','New','Unknown','No','From Base Set','074fdde043ccc90c5c660de750fe2939'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Magenta',1,'Acrylic','New','Unknown','No','From Base Set','578ab9b2fb6fa3a2d985a38e3d0dd035'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Sky Blue',1,'Acrylic','New','Unknown','No','From Base Set','cf088b6ba62086ed8a1e91d5c06c692a'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Faded Ultramarine',1,'Acrylic','New','Unknown','No','From Base Set','a727556cea9079620fc371e36db2aa4b'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Dark Grey Blue',1,'Acrylic','New','Unknown','No','From Base Set','8777f6ea034595965e9232f3085ad201'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Bright Warm Grey',1,'Acrylic','New','Unknown','No','From Base Set','1ffd8f6cbe6829bc561b2e5eb81c9349'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Dark Warm Grey',1,'Acrylic','New','Unknown','No','From Base Set','083957bfd63d9c71cdd2345dbf9cd232'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Golden Brown',1,'Acrylic','New','Unknown','No','From Base Set','73ab72768bbe3c2cb9d5940452e8aa71'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Light Umber',1,'Acrylic','New','Unknown','No','From Base Set','5a1adfb99741633e37651c66fde8db5a'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Dark Umber',1,'Acrylic','New','Unknown','No','From Base Set','426c7b328fa96fd70e372204669f2d17'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Camo Green',1,'Acrylic','New','Unknown','No','From Base Set','dfe49e4f7e843b918bd95167b4bc0229'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Jade',1,'Acrylic','New','Unknown','No','From Base Set','8cf61cde16655a1d2fe738ab0abc5b02'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Bright Ivory',1,'Acrylic','New','Unknown','No','From Base Set','7b815698972407f5d2470d6aa77bbc22'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Ivory',1,'Acrylic','New','Unknown','No','From Base Set','2b3d03795bb8fd1c9f40cfea72708c90'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Base Set','Tan Flesh',1,'Acrylic','New','Unknown','No','From Base Set','9025e46bf4d6379472893b2f109afa5b'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Metallic','Bright Gold',1,'Metallic','New','Unknown','No','Purchased separately','8d74d0ea4277bb13c70707526003f711'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Metallic','Rich Gold',1,'Metallic','New','Unknown','No','Purchased separately','e97a4a5d40cd9e29e1db36c177975352'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Pro Acryl','Metallic','Dark Silver',1,'Metallic','New','Unknown','No','Purchased separately','08999af4186b90b151cec6ee534d26f9'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Game Air','Black',1,'Airbrush Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','8c4a6ff71823a59697704812a192d767'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Game Air','Olive Green',1,'Airbrush Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','087b16450b57ee0bf874180f941d0510'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Game Air','Blue',1,'Airbrush Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','ea677d5bef5b9735489b2384403eecd9'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Game Air','Turquoise',1,'Airbrush Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','5803f738f1464acf9a1ff1a5421f0486'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Game Air','Turquoise',1,'Airbrush Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','90a66704543d139da13a8729ef19e9b5'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Game Air','Sun Yellow',1,'Airbrush Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','bf517ab876a0d842fe34994d4cc1fbb7'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Game Air','Scarlet Red',1,'Airbrush Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','4180ccbfcf50e30a7820dc069807b2ea'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Game Air','Sick Green',1,'Airbrush Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','c848af7ae7d1879bdcb78f8bc503f120'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Game Air','Bloody Red',1,'Airbrush Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','d67b70451525d561e92fe13c1ecb8f10'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Game Air','Heavy Charcoal',1,'Airbrush Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','aa6976abf1d77dd1aa745ea1a86b8227'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Model Color','Azure',1,'Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','9a8952c9b6d6da550a2aa9fa9ab90db3'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Model Color','White',1,'Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','2cfc74b125cfc52b1445a63a1b41f3b0'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Model Color','Yellow',1,'Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','e349ddcea382298274ad4a19e38b93cc'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Model Color','Buff',1,'Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','7a0ded8c5d755c67b9d8bb0c86a0a5a8'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Model Color','Black',1,'Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','64622ffab3674801668c8e5dc571a945'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Model Color','Lemon Yellow',1,'Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','f68cd129e53bbc2b93ea69ae06d18c0c'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Model Color','Flesh',1,'Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','5b44184e3e08610bbcdd9a6a7f0ae17b'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Model Color','Silver',1,'Metallic','Needs Testing','Unknown','Unknown','Recovered from storage','8ee7a6dba29e29fa6e5d18c8ba72fb3e'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Model Color','Gold',1,'Metallic','Needs Testing','Unknown','Unknown','Recovered from storage','7bcd59201bd2b79509cc938367c5b0bd'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Model Color','Red',1,'Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','d8dd17bd098a39dea88f77c226ed4c29'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Model Color','Refractive Green',1,'Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','5c19496e82ed9311a8b04ed8e183f495'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Model Color','Flat Green',1,'Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','2d73b4167b13e3f19b9ff6f018ecb4c0'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Model Color','Purple',1,'Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','8c49404067e64236772d16ff6434e0a5'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Model Color','Flat Yellow',1,'Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','aef192ed80ba1252a7bfa62f143d3cf5'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Model Color','Clear Orange',1,'Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','1a5d8190dff6e219951da96fc86d955e'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Vallejo','Model Color','Blue',1,'Acrylic','Needs Testing','Unknown','Unknown','Recovered from storage','e7eec8ed609b5108e351de23b91caa53'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Green Stuff World','Colorshift','Psychotic Illusions',1,'Colorshift','Needs Testing','Unknown','Unknown','Recovered from storage','ca98131520de442c294f2859845d14f3'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Green Stuff World','Colorshift','Red Copper',1,'Colorshift','Needs Testing','Unknown','Unknown','Recovered from storage','c517a916dd98d8b3eaabb7db71d0a7b0'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Green Stuff World','Colorshift','Psychic Purple',1,'Colorshift','Needs Testing','Unknown','Unknown','Recovered from storage','78c22800686eb6b192d3afd2e1eb2338'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Green Stuff World','Colorshift','Cobalt Blue',1,'Colorshift','Needs Testing','Unknown','Unknown','Recovered from storage','e393ca36c3805055c2977ec958994188'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Green Stuff World','Colorshift','Goblin',1,'Colorshift','Needs Testing','Unknown','Unknown','Recovered from storage','6812861739cb1c7e92dd955fa8ea1474'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Green Stuff World','Colorshift','Celestial Azure',1,'Colorshift','Needs Testing','Unknown','Unknown','Recovered from storage','afc6532abbf0dc56e45684c96feb5c35'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Green Stuff World','Colorshift','Brown Sugar',1,'Colorshift','Needs Testing','Unknown','Unknown','Recovered from storage','01539be4bb4834541f0dead01280144c'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Green Stuff World','Colorshift','Mystic Gold',1,'Colorshift','Needs Testing','Unknown','Unknown','Recovered from storage','5e1634b73658cffd0680cc61d19754fa'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Green Stuff World','Colorshift','Emerald Getaway',1,'Colorshift','Needs Testing','Unknown','Unknown','Recovered from storage','b2b8cbd96ecc3fbe64e49812a264716e'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Green Stuff World','Colorshift','Martian Green',1,'Colorshift','Needs Testing','Unknown','Unknown','Recovered from storage','fafa60195b198cd4fed33a12ec611c8d'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Green Stuff World','Colorshift','Burning Gold',1,'Colorshift','Needs Testing','Unknown','Unknown','Recovered from storage','2cdd6eb3d40e41ef5d9875014cf360f0'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Paint','Green Stuff World','Colorshift','Tropic Green',1,'Colorshift','Needs Testing','Unknown','Unknown','Recovered from storage','a544c5db0b8078e210d4db486b30a63a'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Medium','Vallejo','Model Color','Plastic Putty',1,'Putty','Needs Testing','Unknown','Unknown','Recovered from storage','6fb48d0bc9d35dae721cf01764c6abce'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();
  insert into paints(owner_id,category,brand,line,color_name,quantity,paint_type,condition,opened,needs_replacement,notes,import_key) values (
    v_owner,'Medium','Vallejo','Effects','Varnish Mixing Medium',1,'Medium','Needs Testing','Unknown','Unknown','Recovered from storage','38e9b4694e315ab0759c00f242da139b'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,needs_replacement=excluded.needs_replacement,notes=excluded.notes,updated_at=now();

  -- Brushes
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Citadel','Small Drybrush',NULL,'Synthetic',2,'Fair-Good','Drybrushing','Older colored-cap era','267a013f0b9006fb99120aafa987dfce'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Citadel','Medium Drybrush',NULL,'Synthetic',1,'Fair-Good','Drybrushing','Older colored-cap era','59013be2cbe6281f4ce58a0feae6abe0'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Citadel','Large Drybrush',NULL,'Synthetic',1,'Fair','Drybrushing / terrain','Older colored-cap era','ba4d2ea5ae3b2f81ffbefaece9f2c8cc'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Citadel','Detail Brush',NULL,'Synthetic/Natural Unknown',1,'Good','Detail','Older colored-cap era','0c412f5291cb2f4e15a14747cf91ac7d'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Citadel','Fine Detail Brush',NULL,'Synthetic/Natural Unknown',1,'Good','Fine detail','Older colored-cap era','f6c1d94a3d63e7cd2b94889a1522d579'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Citadel','Layer Brush',NULL,'Synthetic/Natural Unknown',1,'Good','Layering','Older colored-cap era','72500a71a963d6aa2810239b5ad2e97a'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Citadel','Standard Brush',NULL,'Synthetic/Natural Unknown',2,'Good','General painting','Older colored-cap era','bbd6e63680aefa284235e5c490f5e43b'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Citadel','Large Brush',NULL,'Synthetic/Natural Unknown',1,'Fair-Good','Basecoating','Older colored-cap era','2e6e333039ce8ef1ea8d9a2070ad7f27'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Citadel','Basecoat Brush',NULL,'Synthetic',1,'Good','Basecoating','Older colored-cap era','1d88b74edc15d9b30dcfe742abc46dde'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Citadel','Small Basecoat Brush',NULL,'Synthetic',1,'Good','Basecoating','Older colored-cap era','d98d96dc9927bc0a021d0202f6e91de2'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Citadel','Character Brush',NULL,'Synthetic/Natural Unknown',1,'Good','Character/detail','Older colored-cap era','2af320de96045595a52146adaaae8d0c'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Citadel','Wash Brush',NULL,'Synthetic',1,'Fair-Good','Washes','Older colored-cap era','f3d6252d197ade9f58fc2e732ed39060'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Citadel','Glaze Brush',NULL,'Synthetic',1,'Good','Glazes','No marking on back','259701e7dfbdb89d5ff8cdb3b9207198'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Army Painter','Hobby: Standard Brush',NULL,'Synthetic/Natural Unknown',1,'Good','General painting',NULL,'0a109313657fcbc9b10e652f5644acbb'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Army Painter','Hobby: Dry Brush',NULL,'Synthetic',2,'Fair-Good','Drybrushing',NULL,'f45e7c1838df2f756a81036d7c627e46'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Army Painter','Hobby: Small Detail',NULL,'Synthetic/Natural Unknown',1,'Good','Detail',NULL,'13840c6f096b8a9a332b1a83ac1c368b'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Army Painter','Hobby: Highlighting Brush',NULL,'Synthetic/Natural Unknown',1,'Good','Highlights',NULL,'4df316029e486c01efa0769b92a46501'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Dynasty','Eye of the Tiger','12-610','Synthetic',1,'Good','Terrain / broad work',NULL,'e02e3e554683ce8ec7973b39661edc25'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Dynasty','Eye of the Tiger','10-610','Synthetic',1,'Good','Terrain / broad work',NULL,'7420683c40efc67b4c7f61201786b89c'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Dynasty','Eye of the Tiger','8-610','Synthetic',1,'Good','Terrain / broad work',NULL,'479c0cfd84f79720c04cf7ec892222db'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Dynasty','Eye of the Tiger','6-615','Synthetic',1,'Good','Basecoating / utility',NULL,'2f5d4ee37b2687bb99cd17130b940f6a'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Dynasty','Eye of the Tiger','6-610','Synthetic',1,'Good','Basecoating / utility',NULL,'c5204f0dc5488595033e0f5eeb290a68'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Dynasty','Eye of the Tiger','4-610','Synthetic',2,'Good','Basecoating / utility',NULL,'06bad86a9c5aad8184a9fc171fcb2d0c'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Dynasty','Eye of the Tiger','4-615','Synthetic',1,'Good','Basecoating / utility',NULL,'f6ab70257c4035d7f6435fa68a40ce55'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Dynasty','Eye of the Tiger','2-615','Synthetic',1,'Good','Detail / utility',NULL,'f6e2e30371c5aff3ba4413539efde3e4'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Dynasty','Eye of the Tiger','2-610','Synthetic',1,'Good','Detail / utility',NULL,'0c7006a09fd321f78732c2b02fe3a98c'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Reaper','Pro Paint','10/0','Unknown',2,'1 fair, 1 rough','Fine detail / utility','One tip is rough','1cdb66b65b2a6abaf2da3c04a2517cf6'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Winsor & Newton','University Series 233','00','Synthetic/Natural Unknown',1,'Needs cleaning/evaluation','Detail backup','Not Series 7','1974d9344982bc46c78aacdc9c568ca5'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Winsor & Newton','Series 7 (new)','TBD','Kolinsky sable',3,'New','Detail / layering','Recent purchase; exact sizes TBD','c831633d4d6fe5b8e99357eb9d1f7459'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Princeton','Select Liner','0','Synthetic',1,'Good','Lining/detail',NULL,'05b78347e8db86912bc5a79433279dbc'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Golden Taklon','Round','2/0','Synthetic',1,'Good','Detail / utility',NULL,'ab31117ec689fa77c564d52f5c732397'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into brushes(owner_id,manufacturer,series,size,material,quantity,condition,purpose,notes,import_key) values (
    v_owner,'Unknown','Thailand detail brushes',NULL,'Synthetic',3,'Fair/utility','Utility detail','Only marking is Thailand','a3f006f41e8a7f8aba9382c50ce356c3'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();

  -- Tools / Equipment
  insert into tools(owner_id,category,item,quantity,condition,notes,import_key) values (
    v_owner,'Workspace','Standing desk',1,'Functional','Facebook Marketplace; cosmetic damage/chips','36f5da756ba2f9a0d2f3b5432a4a9aca'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into tools(owner_id,category,item,quantity,condition,notes,import_key) values (
    v_owner,'Lighting','Neatfi lamp',1,'Functional','Power switch found','c8f6f67fe4ecdecd130fba64ea918e95'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into tools(owner_id,category,item,quantity,condition,notes,import_key) values (
    v_owner,'Workspace','Cutting/hobby mat',1,'Good','Recovered','508a76b9d2aff47366f3750c289ba09d'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into tools(owner_id,category,item,quantity,condition,notes,import_key) values (
    v_owner,'Organization','64-drawer cabinet',1,'Ordered','Arrives tomorrow','1fd4dd6af61ba8da470d870cf4c40b9b'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into tools(owner_id,category,item,quantity,condition,notes,import_key) values (
    v_owner,'Organization','Plano 3600 Deep organizer',1,'New',NULL,'934d3c33f1d1adcc2ff8b21346ab99f6'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into tools(owner_id,category,item,quantity,condition,notes,import_key) values (
    v_owner,'Assembly Tool','GodHand sprue cutter',1,'New/Good',NULL,'d7bfbcc67af739346377df42f44f6029'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into tools(owner_id,category,item,quantity,condition,notes,import_key) values (
    v_owner,'Assembly Tool','Generic sprue cutters',2,'Good',NULL,'adc7b939707fc25bbf680e95fcfc1eb5'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into tools(owner_id,category,item,quantity,condition,notes,import_key) values (
    v_owner,'Assembly Tool','Hobby knives',3,'Good',NULL,'6a88dd5ca15f347dbfb94d6dedeed98f'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into tools(owner_id,category,item,quantity,condition,notes,import_key) values (
    v_owner,'Assembly Tool','File sets',2,'Good',NULL,'2a6fcdc50cd08f92e21b30ced7ca897d'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into tools(owner_id,category,item,quantity,condition,notes,import_key) values (
    v_owner,'Brush Care','The Master''s Brush Cleaner & Preserver',1,'Good',NULL,'39e330ea63ee885a173551dfefba8057'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into tools(owner_id,category,item,quantity,condition,notes,import_key) values (
    v_owner,'Adhesive','Plastic cement',1,'Good',NULL,'c75c8c24dd016cd98b5cd43b09a6ee8c'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into tools(owner_id,category,item,quantity,condition,notes,import_key) values (
    v_owner,'Airbrush','Iwata Revolution HP-CR',1,'Recovered',NULL,'6fd98003b8f0ad18f54355cdfeef9047'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into tools(owner_id,category,item,quantity,condition,notes,import_key) values (
    v_owner,'Airbrush','Airbrush compressor',1,'Recovered; needs test',NULL,'19e8efb3e0417aa2df61eb433c2307f5'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into tools(owner_id,category,item,quantity,condition,notes,import_key) values (
    v_owner,'Airbrush','Airbrush cleaning kit',1,'Good',NULL,'b1adb46473bee90e76282076ce3c5068'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into tools(owner_id,category,item,quantity,condition,notes,import_key) values (
    v_owner,'Painting','Privateer Press wet palettes',2,'Good',NULL,'bdd5d3e1f6fa69753584f0b0c707e7bc'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into tools(owner_id,category,item,quantity,condition,notes,import_key) values (
    v_owner,'Painting','Privateer Press palette paper pads',3,'Good',NULL,'52d25adddf8f5ff6bcda676d6c5314e4'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into tools(owner_id,category,item,quantity,condition,notes,import_key) values (
    v_owner,'Organization','Brush holder',1,'Needs part','Missing one leg','567cdb83e46425b94c754bceb767e3ee'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into tools(owner_id,category,item,quantity,condition,notes,import_key) values (
    v_owner,'Storage/Transport','Magnets',1,'New','Assorted hobby magnets','07baa0f1497f438ede26048ab9564a0c'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();
  insert into tools(owner_id,category,item,quantity,condition,notes,import_key) values (
    v_owner,'Paint Mixing','304 stainless agitator balls',1,'New',NULL,'8c5dbf8ce0ede98c9a4d0979b8c0e151'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,updated_at=now();

  -- Terrain
  insert into terrain(owner_id,terrain_set,components,quantity,quantity_label,paint_status,repairs_needed,notes,import_key) values (
    v_owner,'Wall of Martyrs','Fortification Components',NULL,'Multiple','Painted','None','Trenches, walls, bunker/emplacements','cca2cd3d214930c03e0dd45514a0141f'
  ) on conflict (owner_id,import_key) do update set quantity=excluded.quantity,paint_status=excluded.paint_status,repairs_needed=excluded.repairs_needed,notes=excluded.notes,updated_at=now();

  raise notice 'Import complete for owner %', v_owner;
end $$;
